import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { createServer, type Server } from "node:http";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { ZincHost, type Event } from "../src/host.js";
import type { Config } from "../src/config.js";

const roots: string[] = [], servers: Server[] = [], encoder = new TextEncoder(), decoder = new TextDecoder();
afterEach(async () => { await Promise.all(servers.splice(0).map((server) => new Promise<void>((resolve) => server.close(() => resolve())))); await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });
async function fixture(options: { turn?: string; completionsUrl?: string; allowlist?: string[]; contextTokens?: number; compactAt?: number; rawContextBytes?: number } = {}) { const root = await mkdtemp(join(tmpdir(), "zinc-host-")); roots.push(root); const turn = join(root, "turn.md"); await writeFile(turn, options.turn ?? `in { context $context }\nrespond source="" { (text)in "done"; (text)out $response }\nout { response $response }\n`); const config: Config = { store: join(root, "zinc.db"), turn, theme: join(process.cwd(), "defaults", "theme.kdl"), url: "localhost", port: 5173, author: "anonymous", completionsUrl: options.completionsUrl ?? "http://127.0.0.1:30000/v1/chat/completions", parallel: 2, rawContextBytes: options.rawContextBytes ?? 8192, contextTokens: options.contextTokens ?? 32768, compactAt: options.compactAt ?? 80, packetOverflowBytes: 65536, shell: "sh", allowlist: options.allowlist ?? [] }; return { root, host: await ZincHost.open(config, root) }; }
const streamingTurn = `in { context $context; completions-url $completions-url }
respond source="$completions-url" { (json)in { stream #true; context $context }; (json)out #"{"choices":[{"delta":{"reasoning_content":"?reasoning","content":"?response"}}]}"# }
out { reasoning ?reasoning; response ?response }
`;
const actionTurn = `in { context $context; completions-url $completions-url }
respond source="$completions-url" { (json)in { stream #true; context $context }; (json)out #"{"choices":[{"delta":{"content":"?response","tool_calls":[{"index":"?call","function":{"arguments":{"kdl":"?circuitry"}}}]}}]}"# }
out { response ?response; circuitry ?circuitry }
`;
const packet = (text: string) => encoder.encode(`${JSON.stringify({ zinc: "text", format: "markdown", text })}\n`);
const patch = (revision: string, text = "hello") => ({ revision, order: ["user"], writes: [{ id: "user", origins: [], bytes: packet(text) }] });

describe("ZincHost v8", () => {
  it("uses configured Runtime capacity and completes one atomic patch", async () => { const { host } = await fixture(); expect(host.runtime.parallel).toBe(2); const created = await host.create(host.config.store), reader = host.events(new AbortController().signal).getReader(); await host.complete(host.config.store, created.id, patch(created.manifest.revision)); await nextType(reader, "done"); const manifest = await host.manifest(host.config.store, created.id); expect(manifest.blocks.some((block) => block.role === "agent")).toBe(true); await host.close(); });

  it("streams transient output and commits durable blocks only after HTTP EOF", async () => { let ended = false; const server = createServer(async (_request, response) => { response.writeHead(200, { "content-type": "text/event-stream" }); response.write('data: {"choices":[{"delta":{"reasoning_content":"thinking "}}]}\n\n'); await delay(20); response.write('data: {"choices":[{"delta":{"content":"hello "}}]}\n\n'); await delay(40); ended = true; response.end('data: {"choices":[{"delta":{"content":"world"}}]}\n\n'); }); const url = await listen(server), { host } = await fixture({ turn: streamingTurn, completionsUrl: url }), created = await host.create(host.config.store), reader = host.events(new AbortController().signal).getReader(); await host.complete(host.config.store, created.id, patch(created.manifest.revision)); expect((await nextType(reader, "reasoning")).text).toBe("thinking "); expect(ended).toBe(false); expect((await nextType(reader, "response")).text).toBe("hello "); await nextType(reader, "done"); expect(ended).toBe(true); expect((await host.manifest(host.config.store, created.id)).blocks.filter((block) => block.role === "agent")).toHaveLength(2); await host.close(); });

  it("keeps packet identities out of raw provider context", async () => { const requests: string[] = []; const server = createServer(async (request, response) => { requests.push(await requestText(request)); response.writeHead(200, { "content-type": "text/event-stream" }); response.end(`data: ${JSON.stringify({ choices: [{ delta: { content: "finished" } }], usage: { prompt_tokens: 11, completion_tokens: 3, total_tokens: 14 } })}\n\n`); }); const url = await listen(server), turn = await readFile(join(process.cwd(), "agent", "turn.md"), "utf8"), { host } = await fixture({ turn, completionsUrl: url }), created = await host.create(host.config.store), reader = host.events(new AbortController().signal).getReader(); await host.complete(host.config.store, created.id, patch(created.manifest.revision, "context")); await nextType(reader, "done"); expect(requests[0]).not.toContain("pkt_"); expect(requests[0]).toContain("### user"); await host.close(); });

  it("stores nested action results and continues", async () => { const requests: string[] = []; const server = createServer(async (request, response) => { requests.push(await requestText(request)); response.writeHead(200, { "content-type": "text/event-stream" }); response.end(requests.length === 1 ? `data: ${JSON.stringify({ choices: [{ delta: { tool_calls: [{ index: 0, function: { arguments: { kdl: 'out { result "ok" }' } } }] } }] })}\n\n` : `data: ${JSON.stringify({ choices: [{ delta: { content: "finished" } }] })}\n\n`); }); const url = await listen(server), { host } = await fixture({ turn: actionTurn, completionsUrl: url }), created = await host.create(host.config.store), reader = host.events(new AbortController().signal).getReader(); await host.complete(host.config.store, created.id, patch(created.manifest.revision)); await nextType(reader, "done"); expect(requests).toHaveLength(2); expect(JSON.parse(requests[1]).context).toContain('"result": "ok"'); await host.close(); });

  it("cancels active completion without persisting an error", async () => { let begin!: () => void; const started = new Promise<void>((resolve) => { begin = resolve; }), server = createServer((request, response) => { response.writeHead(200, { "content-type": "text/event-stream" }); response.flushHeaders(); begin(); request.once("close", () => response.end()); }); const url = await listen(server), { host } = await fixture({ turn: streamingTurn, completionsUrl: url }), created = await host.create(host.config.store), reader = host.events(new AbortController().signal).getReader(); await host.complete(host.config.store, created.id, patch(created.manifest.revision)); await started; expect(host.cancel(host.config.store, created.id)).toBe(true); await nextType(reader, "done"); const manifest = await host.manifest(host.config.store, created.id), blocks = await host.blocks(host.config.store, created.id, manifest.revision, manifest.blocks.map((block) => block.id)); expect(blocks.some((block) => decoder.decode(block.bytes).includes('"format":"error"'))).toBe(false); await host.close(); });

  it("treats provider sentinels as invalid JSON data", async () => { const server = createServer((_request, response) => { response.writeHead(200, { "content-type": "text/event-stream" }); response.end("data: [DONE]\n\n"); }); const url = await listen(server), { host } = await fixture({ turn: streamingTurn, completionsUrl: url }), created = await host.create(host.config.store), reader = host.events(new AbortController().signal).getReader(); await host.complete(host.config.store, created.id, patch(created.manifest.revision)); expect((await nextType(reader, "error")).text).toMatch(/DONE|JSON/); await host.close(); });
});
function requestText(request: import("node:http").IncomingMessage) { return new Promise<string>((resolve) => { let text = ""; request.setEncoding("utf8"); request.on("data", (chunk) => text += chunk); request.on("end", () => resolve(text)); }); }
function delay(ms: number) { return new Promise((resolve) => setTimeout(resolve, ms)); }
async function listen(server: Server) { servers.push(server); await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve)); const address = server.address(); if (!address || typeof address === "string") throw new Error("server did not bind"); return `http://127.0.0.1:${address.port}`; }
async function nextType(reader: ReadableStreamDefaultReader<Uint8Array>, type: Event["type"]): Promise<any> { while (true) { const next = await reader.read(); if (next.done) throw new Error(`event stream ended before ${type}`); const event = JSON.parse(decoder.decode(next.value).slice(6)) as Event; if (event.type === type) return event; } }
