import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { ZincHost } from "../src/host.js";
import { compileTsxPreview, createRequestHandler } from "../src/server.js";
import type { Config } from "../src/config.js";

const roots: string[] = [], encoder = new TextEncoder();
afterEach(() => Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))));
async function fixture() { const root = await mkdtemp(join(tmpdir(), "zinc-server-")); roots.push(root); const turn = join(root, "turn.md"), client = join(root, "client"), fonts = join(client, "fonts"); await mkdir(fonts, { recursive: true }); await writeFile(join(client, "index.html"), "ok"); await writeFile(join(client, "app-12345678.js"), "ok"); await writeFile(join(fonts, "prose.woff2"), "ok"); await writeFile(turn, `out {}`); const config: Config = { store: join(root, "zinc.db"), turn, theme: join(process.cwd(), "defaults", "theme.kdl"), url: "localhost", port: 5173, author: "anonymous", completionsUrl: "http://localhost", parallel: 1, rawContextBytes: 10, contextTokens: 32768, compactAt: 80, packetOverflowBytes: 100, shell: "sh", allowlist: [] }; const host = await ZincHost.open(config, root); return { host, request: createRequestHandler(host, client) }; }
const packet = (text: string) => Buffer.from(encoder.encode(`${JSON.stringify({ zinc: "text", format: "markdown", text })}\n`)).toString("base64");
const post = (value: unknown) => ({ method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(value) });

describe("server v8", () => {
  it("creates manifests, commits stable blocks, and batches payload reads", async () => { const { host, request } = await fixture(), createdResponse = await request(new Request("http://z/api/threads", post({ store: host.config.store }))), created: any = await createdResponse.json(); expect(created.id).toMatch(/^thr_/); const savedResponse = await request(new Request("http://z/api/thread", post({ store: host.config.store, thread: created.id, patch: { revision: created.manifest.revision, order: ["a"], writes: [{ id: "a", origins: [], bytes: packet("hello") }] } }))), saved: any = await savedResponse.json(); expect(saved.manifest.blocks[0]).toMatchObject({ id: "a", role: "user" }); const loaded = await request(new Request("http://z/api/blocks/read", post({ store: host.config.store, thread: created.id, revision: saved.manifest.revision, ids: ["a"] }))); expect(JSON.parse(Buffer.from((await loaded.json() as any).blocks[0].bytes, "base64").toString()).text).toBe("hello"); await host.close(); });
  it("validates patch bytes and stable block source/fork requests", async () => { const { host, request } = await fixture(), created = await host.create(host.config.store); const bad = await request(new Request("http://z/api/thread", post({ store: host.config.store, thread: created.id, patch: { revision: created.manifest.revision, order: ["a"], writes: [{ id: "a", origins: [], bytes: "***" }] } }))); expect(bad.status).toBe(400); await host.close(); });
  it("serves the configured theme and explicit cache policies", async () => { const { host, request } = await fixture(); const theme = await request(new Request("http://z/theme.css")); expect(theme.headers.get("cache-control")).toBe("no-cache"); expect(await theme.text()).toContain("--z-background:#090d12"); expect((await request(new Request("http://z/api/stores"))).headers.get("cache-control")).toBe("no-store"); expect((await request(new Request("http://z/app-12345678.js"))).headers.get("cache-control")).toBe("public, max-age=31536000, immutable"); await host.close(); });
  it("guards previews and static traversal", async () => { const { host, request } = await fixture(); expect(compileTsxPreview(`export default function A(){return <div/>}`)).toMatchObject({ ok: true }); expect(compileTsxPreview(`import fs from "node:fs"; export default function A(){}`)).toMatchObject({ ok: false }); expect((await request(new Request("http://z/%2e%2e%2fsecret"))).status).toBe(400); await host.close(); });
});
