import { describe, expect, it } from "vitest";
import { decodeBlock, documentNodes, encodeBlock, markdownPacket, textPacket } from "../web/src/editor/codec.js";
import { markdownToNodes, nodesToMarkdown } from "../web/src/markdown.js";
import { identifierSuggestion, parseIdentifier, tagColor } from "../web/src/thread/identifier.js";

const encoder = new TextEncoder(), packet = (value: unknown) => encoder.encode(`${JSON.stringify(value)}\n`);
describe("Web block boundary", () => {
  it("projects canonical Markdown without PacketNode or MarkdownMarkerNode", () => { const decoded = decodeBlock(markdownPacket("# Heading\n\n**bold** and [link](https://example.com)")), source = JSON.stringify(decoded.document); expect(source).not.toContain('"type":"packet"'); expect(source).not.toContain('"type":"markdown-marker"'); expect(source).toContain('"detail":2'); expect(encodeBlock("markdown", decoded.document)).toEqual(markdownPacket("# Heading\n\n**bold** and [link](https://example.com)")); });
  it("round trips GFM tables as rich structure with exact source", () => { const source = "| Name | Value |\n| --- | --- |\n| alpha | **one** |", nodes = markdownToNodes(source); expect(nodes[0].type).toBe("table"); expect(nodesToMarkdown(nodes)).toBe(source); });
  it("retains inline and display equation source in EquationNode", () => { const inline = decodeBlock(markdownPacket("Energy $E=mc^2$ today.")), children = documentNodes(inline.document)[0].children as any[]; expect(children.map((child) => child.type)).toEqual(["text", "equation", "text"]); expect(children[1].source).toBe("$E=mc^2$"); expect(JSON.parse(new TextDecoder().decode(encodeBlock("markdown", inline.document))).text).toBe("Energy $E=mc^2$ today."); const display = decodeBlock(markdownPacket("$$\nx^2+y^2\n$$")); expect((documentNodes(display.document)[0].children as any[])[0]).toMatchObject({ type: "equation", source: "$$\nx^2+y^2\n$$" }); });
  it("keeps TSX preview as the default and source as canonical", () => { const decoded = decodeBlock(textPacket("tsx", "export default () => <button>ok</button>")); expect(documentNodes(decoded.document)[0].type).toBe("tsx-preview"); expect(JSON.parse(new TextDecoder().decode(encodeBlock("tsx", decoded.document))).text).toContain("<button>"); });
  it("retains reasoning, shell, recall, and error product nodes", () => { expect(documentNodes(decodeBlock(textPacket("reasoning", "think")).document)[0].type).toBe("reasoning"); expect(documentNodes(decodeBlock(textPacket("error", "bad")).document)[0].type).toBe("error"); expect(documentNodes(decodeBlock(packet({ zinc: "shell", command: "ls", output: "file" })).document)[0].type).toBe("shell"); expect(documentNodes(decodeBlock(packet({ zinc: "recall", packet: "pkt_a", content: "old" })).document)[0].type).toBe("recall"); });
  it("canonicalizes tags first and derives deterministic colors", () => { expect(parseIdentifier("Manuscript #editor #zinc")).toEqual({ value: "#editor #zinc Manuscript", tags: ["#editor", "#zinc"], title: "Manuscript" }); expect(tagColor("#editor")).toBe(tagColor("#editor")); expect(identifierSuggestion("# A **long** manuscript title with more than seven words here").split(" ").length).toBeLessThanOrEqual(7); });
});
