package = "zinc"
version = "0.1.0"
lua = "5.5"

[source]
url = "https://github.com/darkhorseprojects/zinc/archive/refs/tags/v$(VERSION).tar.gz"

[dependencies]
lsqlite3complete = "0.9.7-1"
lunajson = "1.2.3-1"

[build]
type = "builtin"

[build.modules]
"zinc" = "package/zinc.md"
"design" = "package/design.md"
"presets.unsafe" = "package/presets/unsafe.md"
"presets.safe" = "package/presets/safe.md"
"presets.no-host" = "package/presets/no-host.md"
"src.entry" = "package/src/entry.lua"
"src.memory" = "package/src/memory.lua"
"src.model" = "package/src/model.lua"
"src.run" = "package/src/run.lua"
"src.store" = "package/src/store.lua"
