import * as stylex from "@stylexjs/stylex";
import { corners, palette, type } from "../styles/design.stylex";

export const threadStyles = stylex.create({
  forks: { position: "absolute", right: "calc(100% + 44px)", top: "3px", display: "flex", alignItems: "center", gap: "4px", width: "max-content", whiteSpace: "nowrap" },
  gutter: { position: "absolute", inset: 0, zIndex: 5, pointerEvents: "none" },
  gutterButton: { position: "absolute", top: 0, width: "24px", height: "24px", pointerEvents: "auto", willChange: "transform, opacity" },
  gutterHandle: { right: "calc(100% + 16px)" },
  gutterNew: { right: "calc(100% + 48px + var(--fork-offset, 0px))" },
  sourceRegion: { position: "relative", marginTop: "8px" },
  sourceTags: { display: "flex", flexWrap: "wrap", gap: "4px" },
  sourceTag: {
    height: "20px",
    maxWidth: "12rem",
    paddingTop: "2px",
    paddingRight: "6px",
    paddingBottom: "2px",
    paddingLeft: "6px",
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: palette.border,
    borderRadius: corners.pill,
    color: "rgb(var(--z-muted-rgb) / 0.84)",
    backgroundColor: "transparent",
    fontFamily: type.mono,
    fontSize: "10px",
    lineHeight: 1.3,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    ":hover": { borderColor: "rgb(var(--z-line-rgb) / 0.22)", color: palette.text },
    ":focus-visible": { outlineWidth: "1px", outlineStyle: "solid", outlineColor: palette.focus, outlineOffset: "2px" },
    ":disabled": { opacity: .36 },
  },
});
